<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>28e73c5a-37a6-46d9-850e-577f7365e6bf</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
	</ItemGroup>

</Project>